name: Model Architecture Checks

on:
  push:
    paths:
      - 'mnist_working_model.py'
  pull_request:
    paths:
      - 'mnist_working_model.py'

jobs:
  model-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Model Architecture Checks
      run: python model_checks.py